upstream content-server {
    server content-server:6969;
}

upstream lamb2 {
    server lamb2:7272;
}

upstream system_metrics {
    server cadvisor:8080;
}

upstream postgres_metrics {
    server postgres-exporter:9187;
}

upstream node_metrics {
    server node-exporter:9100;
}
